### 🔹 Gerar Token JWT
POST https://localhost:7039/api/v1/auth/token
Content-Type: application/json

{
  "username": "henrique",
  "password": "123"
}

### COPIE O TOKEN GERADO E COLOQUE NO HEADER ABAIXO ###


### 🔹 Criar um novo Pátio
POST https://localhost:7039/api/v1/Patio
Authorization: Bearer SEU_TOKEN_AQUI
Content-Type: application/json

{
  "nome": "Pátio Central"
}

### Listar todos os Pátios
GET https://localhost:7039/api/v1/Patio
Authorization: Bearer SEU_TOKEN_AQUI

### Listar Pátios com paginação
GET https://localhost:7039/api/v1/Patio/paginado?page=1&pageSize=2
Authorization: Bearer SEU_TOKEN_AQUI

### Buscar Pátio por ID
GET https://localhost:7039/api/v1/Patio/{id}
Authorization: Bearer SEU_TOKEN_AQUI

### Atualizar Pátio
PUT https://localhost:7039/api/v1/Patio
Authorization: Bearer SEU_TOKEN_AQUI
Content-Type: application/json

{
  "id": "{id}",
  "nome": "Patio Atualizado"
}

### Deletar Pátio
DELETE https://localhost:7039/api/v1/Patio/{id}
Authorization: Bearer SEU_TOKEN_AQUI


### Criar Zona
POST https://localhost:7039/api/v1/Zona
Authorization: Bearer SEU_TOKEN_AQUI
Content-Type: application/json

{
  "nome": "Zona A",
  "patioId": "{idPatio}"
}

### Listar Zonas
GET https://localhost:7039/api/v1/Zona
Authorization: Bearer SEU_TOKEN_AQUI

### Listar Zonas com paginação
GET https://localhost:7039/api/v1/Zona/paginado?page=1&pageSize=5
Authorization: Bearer SEU_TOKEN_AQUI

### Buscar Zona por ID
GET https://localhost:7039/api/v1/Zona/1
Authorization: Bearer SEU_TOKEN_AQUI

### Atualizar Zona
PUT https://localhost:7039/api/v1/Zona
Authorization: Bearer SEU_TOKEN_AQUI
Content-Type: application/json

{
  "id": 1,
  "nome": "Zona Atualizada",
  "patioId": "{idPatio}"
}

### Deletar Zona
DELETE https://localhost:7039/api/v1/Zona/1
Authorization: Bearer SEU_TOKEN_AQUI


### Criar Moto
POST https://localhost:7039/api/v1/Moto
Authorization: Bearer SEU_TOKEN_AQUI
Content-Type: application/json

{
  "modelo": "CG 160 Fan",
  "placa": "XYZ1B23",
  "zonaId": 1
}

### Listar Motos
GET https://localhost:7039/api/v1/Moto
Authorization: Bearer SEU_TOKEN_AQUI

### Listar Motos com paginação
GET https://localhost:7039/api/v1/Moto/paginado?page=1&pageSize=5
Authorization: Bearer SEU_TOKEN_AQUI

### Buscar Moto por ID
GET https://localhost:7039/api/v1/Moto/{id}
Authorization: Bearer SEU_TOKEN_AQUI

### Atualizar Moto
PUT https://localhost:7039/api/v1/Moto
Authorization: Bearer SEU_TOKEN_AQUI
Content-Type: application/json

{
  "id": "{idMoto}",
  "modelo": "CG 160 Fan Atualizada",
  "placa": "XYZ1D23",
  "zonaId": 1
}

### Deletar Moto
DELETE https://localhost:7039/api/v1/Moto/{id}
Authorization: Bearer SEU_TOKEN_AQUI


### Predict ML
POST https://localhost:7039/api/v1/Moto/predict
Authorization: Bearer SEU_TOKEN_AQUI
Content-Type: application/json

{
  "modelo": "Yamaha Fazer"
}
